# Generated by Django 3.1.4 on 2020-12-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20201217_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='대한민국', max_length=120),
        ),
    ]
