# Generated by Django 3.1.4 on 2020-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201217_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=1000),
        ),
    ]
