# Generated by Django 3.1.3 on 2020-11-24 03:15

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201123_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\pc\\Desktop\\heroku\\media_root\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
